### PR TITLE
removed xtend

### PR DESCRIPTION
**Pull request by jimmywarting**
replaced with `Object.assign`

### CODE REVIEW

**Comment by jimmywarting** [comment]
I didn't know about Hacktoberfest until now. Since I'm contributing a lot now lately, I figured sure, why not join.

My stats: https://hacktoberfest.digitalocean.com/stats/jimmywarting

**Comment by DiegoRBaquero** [comment]
great!

**Comment by jimmywarting** [comment]
should it be tagged with hacktoberfest?

**Comment by DiegoRBaquero** [comment]
no need, but if you can tag some issues where we could get help, that'd be awesome. I've configured the label in the main repo only with orange color.

**Pull request merged**
