### PR TITLE
Added an image to show the tracker dashboard

### PR DESCRIPTION
**Pull request by Hrafnkellos**

### CODE REVIEW

**Comment by Hrafnkellos** [comment]
I was going to try to rename to lower case but windows has a problem with renaming to upper/lower case and git T_T , but ill will probably cancel this pull request and make and create another one with the comments taken in consideration after work.


I was also thinking about doing something for the UI, maby adding some Webtorrent styling B).

**Comment by alxhotel** [comment]
Thanks, @Hrafnkellos.

Yes please, adding some styles would be greatly appreciated :)

**Comment by DiegoRBaquero** [comment]
Image should merged and pointed to this repo, use relative path. Some styling would be nice.

**Comment by Hrafnkellos** [comment]
closing this one.

**Pull request closed without merging**
