### PR TITLE
Use µWS - Fix #175

### LINKED ISSUE #175: Improve performance & lower memory usage
Although we have made several improvements and clear memory leaks, everything can always be improved.

In order for the webtorrent-webrtc-based projects to reach more users easily, the trackers need to be able to scale with greater performance.

At the time of writing, 1K connected users go for about 500MB of RAM and each connected user is around 0.45MB (BTorrent's tracker)

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
Memory usage improvement by using µWS

### CODE REVIEW

**Comment by lpinca** [comment]
I think you can also remove `socket.on('error', socket.onErrorBound)` as there is no `error` event in `uws`.

**Comment by DiegoRBaquero** [comment]
@lpinca Are you sure? Then why would it allow you to set a [handler](https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/uws.js#L137)? 

Maybe the error is thrown by the native socket and forwarded? There's no message emit either on the nodejs code.

**Comment by DiegoRBaquero** [comment]
@feross need review

**Comment by lpinca** [comment]
@DiegoRBaquero yes I'm sure.

**Comment by lpinca** [comment]
@DiegoRBaquero 
```js
'use strict';

const uWebSocket = require('uws');
const assert = require('assert');

const server = new uWebSocket.Server({ port: 3000 }, () => {
  console.log('server listening on *:3000');
});

server.on('connection', (ws) => {
  const onmessage = () => {};
  const onerror = () => {};

  ws.on('message', onmessage);
  assert.strictEqual(onmessage, ws.internalOnMessage);

  ws.on('error', onerror);
  assert.strictEqual(onerror, ws.internalOnError); // Throws
});
```

**Comment by alexhultman** [comment]
What happened with this? I thought you wanted to solve your memory issues

**Comment by DiegoRBaquero** [comment]
Waiting on @feross . I'm using the changes in BTorrent's tracker.

**Comment by DiegoRBaquero** [comment]
@feross

**Pull request closed without merging**
