### PR TITLE
feat: updated webrtc implementation

### PR DESCRIPTION
**Pull request by ThaUnknown**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Include WebRTC on node, drop wrtc
**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by ThaUnknown** [comment]
> * @SocketSecurity ignore npm/node-datachannel@0.7.0

@SocketSecurity ignore npm/node-datachannel@0.7.0

**Comment by ThaUnknown** [comment]
> **🚨 Potential security issues detected.** Learn more about [Socket for GitHub ↗︎](https://socket.dev?utm_medium=gh)
> 
> To accept the risk, merge this PR and you will not be notified again.
> 
> Alert	Package	Note	Source
> [ Install scripts ](https://socket.dev/npm/package/node-datachannel/alerts/0.7.0?alert_name=installScripts)	[ npm/node-datachannel@0.7.0 ](https://socket.dev/npm/package/node-datachannel/overview/0.7.0)	
> * **Install script:** [install](https://socket.dev/npm/package/node-datachannel/overview/0.7.0)
> * **Source:** `prebuild-install -r napi || (npm install --ignore-scripts --production=false && npm run _prebuild)`
> 
> * [`package.json`](https://github.com/webtorrent/bittorrent-tracker/pull/519/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
> 
> [**View full report↗︎**](https://socket.dev/dashboard/org/gh/webtorrent/diff/e58aa329-f308-4a48-94d9-86d744ea39b2/fe0aab5d-9f13-4dec-94e8-ea8ee7df4025)
> 
> ### Next steps
> ** What is an install script? **
> ** Take a deeper look at the dependency **
> ** Remove the package **
> **Mark a package as acceptable risk**

@SocketSecurity ignore npm/node-datachannel@0.7.0

**Review by SilentBot1 — APPROVED** [review]

**Comment by jarylc** [comment]
It seems after this change which indirectly depends on npm/node-datachannel@0.7.0, the total dependency size has shot up substantially from this dependency alone (likely due to the new compilation steps)
```
ncdu 1.20 ~ Use the arrow keys to navigate, press ? for help                                                                                                                                                                                                                                                     
--- /usr/local/lib/node_modules/bittorrent-tracker/node_modules ---
                                                          /..                                                                                                                                                                                                                                                    
  655.8 MiB [###########################################] /node-datachannel
    8.7 MiB [                                           ] /web-streams-polyfill
  772.0 KiB [                                           ] /utf-8-validate
  428.0 KiB [                                           ] /bufferutil
  316.0 KiB [                                           ] /ip-address
  268.0 KiB [                                           ] /semver
  228.0 KiB [                                           ] /socks
  220.0 KiB [                                           ] /@thaunknown
  212.0 KiB [                                           ] /event-target-shim
  188.0 KiB [                                           ] /readable-stream
  180.0 KiB [                                           ] /ws
  168.0 KiB [                                           ] /smart-buffer
  164.0 KiB [                                           ] /node-domexception
*Total disk usage: 670.2 MiB   Apparent size: 611.1 MiB   Items: 23506
```
I think it's a good idea to take note of this.

**Comment by ThaUnknown** [comment]
not sure what to tell you
image

**Comment by jarylc** [comment]
> not sure what to tell you image

Hmm that's very weird, maybe it's only on OSes that require compilation or some sort (Alpine Linux in this case)

I did notice there was a prebuilt folder in the node module, folder maybe it's using that for Windows and compiles on Linux.

**Comment by ThaUnknown** [comment]
I think this is something to bring up with [node-datachannel,](https://github.com/murat-dogan/node-datachannel/) not webtorrent

**Comment by jarylc** [comment]
> I think this is something to bring up with [node-datachannel,](https://github.com/murat-dogan/node-datachannel/) not webtorrent

Yep do agree, will raise an issue there.

**Comment by Chocobozzz** [comment]
Hi,

Like said above, this PR adds `node-datachannel` dependency (used by `webrtc-polyfill ` introduced by `@thaunknown/simple-peer > 10`) which can break dependency installation on some distributions.

I don't think `simple-peer` (and so `bittorrent-tracker`) should require the prebuilt `node-datachannel` dependency, especially in the case of `bittorrent-tracker` where it may be used in server mode only (where `simple-peer` is not used) or in web browser context.

**Comment by ThaUnknown** [comment]
> where `simple-peer` is not used

it is used, ws trackers were always supported in node.js, simply webrtc wasn't, now that it is, ws trackers work correctly too

**Comment by Chocobozzz** [comment]
I meant using the bittorrent-tracker by just importing the `Server` from https://github.com/webtorrent/bittorrent-tracker/blob/master/server.js

From what I can see `simple-peer` is not used in the server files, but I may be wrong?

**Comment by ThaUnknown** [comment]
right, but there's no package separation between server and client, anyways this isn't changing, it's staying

ndc compiles just fine on alpine so idk what the issue is

**Comment by Chocobozzz** [comment]
> ndc compiles just fine on alpine so idk what the issue is

Unfortunately there are other build issues, on FreeBSD this time: https://github.com/Chocobozzz/PeerTube/issues/6502

I'm not sure to understand why your `simple-peer` package doesn't use the `wrtc` option so it's the responsibility of the library consumer to choose if it wants the native webrtc dependency?

Because the new bittorrent-tracker versions force every consumer to install a native dependency for a very specific use case (use the bittorrent-tracker in client mode, in a node.js ecosystem where webrtc is not available).

What do you think of publishing another package that would not rely on `node-datachannel`, `@thaunknown/simple-peer-lite` for example, that `bittorrent-tracker` may use?

**Pull request merged**
