### PR TITLE
chore(git): add gitignore

### PR DESCRIPTION
**Pull request by alxhotel**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[ ] New feature
[X] Other, please explain:

**What changes did you make? (Give an overview)**
Add missing `.gitignore` similar to other repositories

**Which issue (if any) does this pull request address?**
None

**Is there anything you'd like reviewers to focus on?**
None

### CODE REVIEW

**Review by DiegoRBaquero — APPROVED** [review]

**Comment by alxhotel** [comment]
Yep, good point @DiegoRBaquero. I have updated the PR

**Comment by feross** [comment]
@DiegoRBaquero When people install the CLI app, don't they just use `npm install bittorrent-tracker`? The `package-lock.json` won't be used if they install from npm.

**Comment by DiegoRBaquero** [comment]
> @DiegoRBaquero When people install the CLI app, don't they just use `npm install bittorrent-tracker`? The `package-lock.json` won't be used if they install from npm.

You are right, none of our module are apps where we run `npm install`, and now that we have pinned dev deps, doesn't makes sense to have it

**Pull request merged**
