### PR TITLE
Show clients IP on stats page

### PR DESCRIPTION
**Pull request by bestdeveloperever**
It's helpful to see ip addresses of connected peers.

### CODE REVIEW

**Comment by DiegoRBaquero** [comment]
I would rather not do this as the stats page is publicly available. You can however extend the server to implement this on your own. @feross thoughts?

**Comment by bestdeveloperever** [comment]
Would it be better to have option to enable it? So by default it could be disabled.

**Comment by DiegoRBaquero** [comment]
I'll take is as configurable, default in false. @feross ?

**Comment by feross** [comment]
Sure. If this is defaulted to `false`, we can accept it.

**Comment by Slender1808** [comment]
could have an option with authentication

**Comment by Slender1808** [comment]
Is there currently any api?

**Pull request closed without merging**
